Update README.md
vtex-apps/place-components pull request #31
Opened 2020-11-27 00:22 UTC by caetano1

Update the readme file to match the vtex-apps template, and add the warning message that this is an unfinished app.

#### What problem is this solving?

#### How should this be manually tested?

N/A

#### Checklist/Reminders

- [x] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Jira story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-12-07 17:01 UTC, guerreirobeatriz requested changes

2020-12-07 17:01 UTC, guerreirobeatriz commented on docs/README.md
> +TBC
The text above should be organized within this section.

2020-12-07 17:01 UTC, guerreirobeatriz commented on docs/README.md
> +TBC
```suggestion
🚧 To be defined.
```

2020-12-17 20:10 UTC, caetano1 commented on docs/README.md
>  The `DeviceCoordinates` component renders a simple button that will ask for your permission to get the location from your device. In case the user allows this, the component will modify the address o
As it is still under construction, we will do it as soon as possible 🙏 
For now, it is mostly important to update the warning

2020-12-18 14:55 UTC, guerreirobeatriz approved these changes

2021-02-11 13:27 UTC, lucasecdb approved these changes

2021-02-11 13:28 UTC, merged